# Generated by Django 5.2.5 on 2025-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_user_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='key',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
