# Generated by Django 5.2.5 on 2025-09-07 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_usertoken_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_receipt',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_hours',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Paid', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='User'),
        ),
    ]
