# Generated by Django 5.2.5 on 2025-09-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Worker',
        ),
    ]
