# Generated by Django 5.2.5 on 2025-09-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_company_name_employer_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlog',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='paymentrate',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='paymentrate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proofofwork',
            name='task',
        ),
        migrations.RemoveField(
            model_name='proofofwork',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='worklog',
            name='user',
        ),
        migrations.AlterField(
            model_name='payrollreport',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_reports', to='core.employer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.employer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='core.user'),
        ),
        migrations.AlterField(
            model_name='taskcompletion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='TransactionLog',
        ),
        migrations.DeleteModel(
            name='PaymentRate',
        ),
        migrations.DeleteModel(
            name='ProofOfWork',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
