# Generated by Django 5.2.5 on 2025-09-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_transactionlog_payment_and_more'),
        ('payments', '0002_alter_payment_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='WorkLog',
        ),
    ]
