# Generated by Django 5.2.5 on 2025-09-23 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_worker_delete_worklog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payrollreport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='taskcompletion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='taskcompletion',
            name='task_name',
        ),
        migrations.AddField(
            model_name='employer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='employer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='payrollreport',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='completion_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.task'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.contract')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('cover_letter', models.TextField()),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.CharField(help_text='Comma-separated list of skills', max_length=255)),
                ('experience', models.TextField(blank=True, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to='core.user')),
            ],
        ),
    ]
