# Generated by Django 5.2.5 on 2025-09-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_user_task_assigned_user_remove_employer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employer_profiles/')),
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='phoneNo',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contract',
            name='employer_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='freelancer_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
