# Generated by Django 5.2.5 on 2025-09-30 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.employer'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
