# Generated by Django 5.2.5 on 2025-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_employerprofile_employer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='cover_letter',
        ),
        migrations.AddField(
            model_name='proposal',
            name='cover_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='cover_letters/'),
        ),
    ]
