# Generated by Django 5.2.5 on 2025-10-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_proposal_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
