# Generated by Django 5.2.5 on 2025-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_task_budget_task_category_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='estimated_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
